" Don't try to be vi compatible
set nocompatible

" Helps force plugins to load correctly when it is turned back on below
filetype on

" TODO: Load plugins here (pathogen or vundle)
call plug#begin('~/vimfiles/plugged')
Plug 'preservim/nerdtree'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
call plug#end()

" Turn on syntax highlighting
syntax on

" For plugins to load correctly
filetype plugin indent on

" TODO: Pick a leader key
" let mapleader = ","

" Security
set modelines=0

" Show line numbers
set number

" use system clipboard
set clipboard=unnamed

" Show file stats
set ruler

" Blink cursor on error instead of beeping (grr)
""set visualbell
set noerrorbells

"set pairs
""inoremap ' ''<ESC>ha
""inoremap " ""<ESC>ha
""inoremap ` ``<ESC>ha
""inoremap ( ()<ESC>ha
""inoremap { {}<ESC>ha
""inoremap [ []<ESC>ha
""inoremap /* /** */<ESC>2ha

" Encoding
set encoding=utf-8
set fileencoding=utf-8

"Backup Options
set noswapfile
set nobackup
set undodir=~/vimfiles/undodir
set undofile

"extra 
set noshowmode
set completeopt=menuone,noinsert,noselect
set mouse=a

" Whitespace
set wrap
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set smarttab

""set textwidth=79
set formatoptions=tcqrn1
set noshiftround
set autoindent
set smartindent

" Cursor motion
set scrolloff=3
set backspace=indent,eol,start

" Move up/down editor lines
nnoremap j gj
nnoremap k gk

" Allow hidden buffers
set hidden

" Rendering
set ttyfast

" Status bar
set laststatus=2

" Last line
"set showmode
set showcmd

" Searching
nnoremap / /\v
vnoremap / /\v
set nohlsearch
set incsearch
set ignorecase
set smartcase
set showmatch
map <leader><space> :let @/=''<cr> " clear search

" Remap help key.
inoremap <F1> <ESC>:set invfullscreen<CR>a
nnoremap <F1> :set invfullscreen<CR>
vnoremap <F1> :set invfullscreen<CR>

" Textmate holdouts

" Formatting
map <leader>q gqip

" Disable autoindent when pasting text
let &t_SI .= "\<Esc>[?2004h"
let &t_EI .= "\<Esc>[?2004l"

" Visualize tabs and newlines
set listchars=tab:▸\ ,eol:¬
" Uncomment this to enable by default:
" set list " To enable by default
" Or use your leader key + l to toggle on/off
map <leader>l :set list!<CR> " Toggle tabs and EOL

set splitbelow splitright
 
   " Remap splits navigation to just CTRL + hjkl
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
       
" Make adjusing split sizes a bit more friendly
noremap <silent> <C-Left> :vertical resize +3<CR>
noremap <silent> <C-Right> :vertical resize -3<CR>
noremap <silent> <C-Up> :resize +3<CR>
noremap <silent> <C-Down> :resize -3<CR>
             
" Change 2 split windows from vert to horiz or horiz to vert
 map <Leader>th <C-w>t<C-w>H
 map <Leader>tk <C-w>t<C-w>K

" Color scheme (terminal)
set t_Co=256
set t_ut=
"colorscheme molokai
set background=dark

"VIM Airline Configuration
let g:airline_theme='minimalist'
