#+TITLE: NitishTalks Emacs Config
#+AUTHOR: Nitish Kumar Pattanaik

* Startup Performance

  #+begin_src emacs-lisp

;; The default is 800 kilobytes.  Measured in bytes.
(setq gc-cons-threshold (* 50 1000 1000))

(defun efs/display-startup-time ()
  (message "Emacs loaded in %s with %d garbage collections."
           (format "%.2f seconds"
                   (float-time
                     (time-subtract after-init-time before-init-time)))
           gcs-done))

(add-hook 'emacs-startup-hook #'efs/display-startup-time)


  #+end_src
* PACKAGE MANAGEMENT
** Package System Setup
   Emacs has a built in package manager but it doesn’t make it easy to automatically install packages on a new system the first time you pull down your configuration.

   #+begin_src emacs-lisp
      (require 'package)
   (setq package-archives '(("melpa" . "https://melpa.org/packages/")
			    ("org" . "https://orgmode.org/elpa/")
			    ("elpa" . "https://elpa.gnu.org/packages/")))
   (package-initialize)
   (unless package-archive-contents
     (package-refresh-contents))

   #+end_src 

** Installing use-package
 [[https://github.com/jwiegley/use-package][use-package]] is a really helpful package used in this configuration to make it a lot easier to automate the installation and configuration of everything else we use.
   
   #+begin_src emacs-lisp
   (unless (package-installed-p 'use-package)
      (package-install 'use-package))

    (require 'use-package)
    (setq use-package-always-ensure t)
   #+end_src
** Automatic Package Updates
   The auto-package-update package helps us keep our Emacs packages up to date! It will prompt you after a certain number of days either at startup or at a specific time of day to remind you to update your packages.

You can also use ~M-x auto-package-update-now~ to update right now!

#+begin_src emacs-lisp

  (use-package auto-package-update
    :ensure t
    :custom
    (auto-package-update-interval 7)
    (auto-package-update-prompt-before-update t)
    (auto-package-update-hide-results t)
    :config
    (auto-package-update-maybe)
    (auto-package-update-at-time "09:00"))


#+end_src
* SET UTF-8 EVERYWHERE

** Line Feed Instead Of Carriage return


   #+begin_src emacs-lisp
   (setq-default buffer-file-coding-system 'utf-8-unix)
   #+end_src

** UTF-8 Everywhere
   #+begin_src emacs-lisp
   (set-terminal-coding-system 'utf-8)
(set-language-environment 'utf-8)
(set-keyboard-coding-system 'utf-8)
(prefer-coding-system 'utf-8)
(setq locale-coding-system 'utf-8)
(set-default-coding-systems 'utf-8)
(set-terminal-coding-system 'utf-8)
   #+end_src

** General Keybindings
[[https://github.com/noctuid/general.el][General.el]] allows us to set keybindings.  As a longtime Doom Emacs user, I have grown accustomed to using SPC as the prefix key.  General makes setting keybindings (especially with SPC) much easier.  All of the keybindings we set later in the config depend on general being loaded.

#+begin_src emacs-lisp
(use-package general
  :ensure t
  :config
  (general-evil-setup t)

  (general-create-definer dw/leader-key-def
    :keymaps '(normal insert visual emacs)
    :prefix "SPC"
    :global-prefix "C-SPC")

  (general-create-definer dw/ctrl-c-keys
    :prefix "C-c")
  )
#+end_src

  
* FONTS
  I am using the Fira Code and Cantarell fonts for this configuration which will more than likely need to be installed on your machine. Both can usually be found in teh various Linux distro package managers or dowloaded from the below links. Here FiraCode Nerd Font refers to the Retina font face of the fira code font. And I'm using it on Windows.
[[https://github.com/tonsky/FiraCode][Fira Code Retina]] 
  #+begin_src emacs-lisp
  ;;  (set-face-attribute 'default nil
  ;;	    :font "FiraCode Nerd Font 11"
  ;;	    :weight 'medium)
  ;;  (set-face-attribute 'variable-pitch nil
  ;;	    :font "FiraCode Nerd Font 11"
  ;;	    :weight 'medium)
  ;;  (set-face-attribute 'fixed-pitch nil
  ;;	    :font "Iosevka Aile"
  ;;	    :weight 'regular)

    ;;(setq-default line-spacing 0.10)

    ;; Needed if using emacsclient, Otherwise, your fonts will be smaller tha expected.
    (add-to-list 'default-frame-alist '(font . "FiraCode Nerd Font 11"))


  (set-face-attribute 'default nil
			 :font "JetBrains Mono"
			 :weight 'medium
			;;  :height 110
  )
  ;; Set the fixed pitch face
  (set-face-attribute 'fixed-pitch nil
		      :font "JetBrains Mono"
		      :weight 'medium
		    ;;  :height 110
  )
  ;; Set the variable pitch face
  (set-face-attribute 'variable-pitch nil
		      ;; :font "Cantarell"
		      :font "Iosevka Aile"
		    ;;  :height 120
		      :weight 'medium)
#+end_src

* BUFFER And BOOKMARKS Keybindigs set

  I will do it later in future. First I want to learn all the keybindings of the GNU/Emacs(default keybindings).

* Command Log Mode

  [[https://github.com/lewang/command-log-mode][command-log-mode]] is useful for displaying a panel showing each key binding you use in a panel on the right side of the frame. Great for live streams and screencasts!
  #+begin_src emacs-lisp
  (use-package command-log-mode
  :commands command-log-mode)
  #+end_src
* DASHBOARD
** Dependencies
*** all-the-icons
In windows, you have to install manually all the fonts downloaded by all-the-icons package, in your choosen directory. Just install that, and you are done.
But in linux, it is so easy. You don't need to manually install fonts. It installs font automatically in /usr/share/fonts directory.
  #+begin_src emacs-lisp
  (use-package all-the-icons
   :ensure t)
  #+end_src
*** Projectile
    This part is very much essential. Don't just write use-package projectile. This doesn't work. Just copy this snippet from the official projectile website. Don't mess with it. Otherwise you can't access projectile.

    [[https://projectile.mx/][Projectile]] is a project management library for Emacs which makes it a lot easier to navigate around code projects for various language. Many packages integrate with Projectile so it's a good ideas to have it installed even if you don't use it commands directly.

    #+begin_src emacs-lisp

    (use-package projectile
      :diminish projectile-mode
      :config (projectile-mode)
      :custom ((projectile-completion-system 'ivy))
      :bind-keymap
      ("C-c p" . projectile-command-map)
      :init
      (projectile-mode +1)
      ;; NOTE: Set this to the folder where you keep your Git repos!
      (when (file-directory-p "~/Projects/Code")
	(defvar projectile-project-search-path '("~/Projects/Code")))
      (defvar projectile-switch-project-action #'projectile-dired))

    (use-package counsel-projectile
      :after projectile
      :config (counsel-projectile-mode))
;; Some keybindings using general.el
(dw/leader-key-def
  "pf"  'projectile-find-file
  "ps"  'projectile-switch-project
  "pF"  'consult-ripgrep
  "pp"  'projectile-find-file
  "pc"  'projectile-compile-project
  "pd"  'projectile-dired)

    #+end_src


*** page-break-lines
 not in need now..

** Dashboard Code
   After writing this code just save it and load-file ~/.emacs.d/init.el file. Theen create a new buffer by C-x b named as *dashboard* and refresh that buffer with the command M-x dashboard-refresh-buffer. Then you can see all your customized dashboard. That's it. Nothing else you have to do. ENJOY!
   #+begin_src emacs-lisp
     (use-package dashboard
       :ensure t
       :init
       (progn
	 (setq dashboard-items '((recents . 5)
				 (agenda . 5)
				 (bookmarks . 3)
				 (projects . 3)
				 (registers . 3)))
	 (setq dashboard-set-heading-icons t)
	 (setq dashboard-set-file-icons t)
	 (setq dashboard-banner-logo-title "Emacs Is More Than A Text Editor!")
         ;; (setq dashboard-set-navigator t)
;;	 (setq dahsboard-startup-banner "  c:/Users/Patta/AppData/Roaming/.emacs.d/emacs-logo-transparent.png")
(setq dashboard-startup-banner "~/.emacs.d/emacs-logo-transparent.png")
 (setq dashboard-center-content nil)
	 )
       :config
       (dashboard-setup-startup-hook))
   #+end_src
* Zooming IN and OUT
You can use the bindings CTRL plus =/- for zooming in/out. You can also use CTRL plus
the mouse scroll for zooming in and out.

  #+begin_src emacs-lisp
  ;; zoom in/out like we do everywhere else.
  (global-set-key (kbd "C-=") 'text-scale-increase)
  (global-set-key (kbd "C--") 'text-scale-decrease)
  ;;
  #+end_src


* Graphical User Interface Settings

** Disable Menu, Tool and scroll bar
  #+begin_src emacs-lisp
  ;;(menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
  #+end_src

** Display Line Numbers and Truncated Lines
  #+begin_src emacs-lisp
  (global-display-line-numbers-mode 1)
  (global-visual-line-mode t)
  #+end_src


* THEME
[[https://github.com/hlissner/emacs-doom-themes][doom-themes]] is a great set of themes with a lot of variety an support for many different Emacs modes. You can also run ~M-x counsel-load-theme~ to choose between them easily.
  #+begin_src emacs-lisp
  (use-package doom-themes
     :ensure t)
  (setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
	doom-themes-enable-italic t) ; if nil, italic is universally disabled
;;  (load-theme 'doom-one t)
  (load-theme 'doom-palenight t)
  #+end_src

* Doom MODE_LINE
[[https://github.com/seagle0128/doom-modeline][doom-modeline]] is a very attractive and rich (yet still minimal) mode line configuration for Emacs. The default configuration is quite good but can check out the [[https://github.com/seagle0128/doom-modeline#customize][configuration options]] for more things you can enable or disable.

*NOTE*: The first time ou load your configuration on a new machine, you'll need to run 'M-x all-the-icons-install-fonts' so that mode line icons display correctly. Hence it need all-the-icons package( I already installed)

 #+begin_src emacs-lisp

;; You must run (all-the-icons-install-fonts) one time after
;; installing this package!

(use-package minions
  :hook (doom-modeline-mode . minions-mode))

(use-package doom-modeline

 :init (doom-modeline-mode 1)
  :custom-face
  (mode-line ((t (:height 0.90))))
  (mode-line-inactive ((t (:height 0.90))))
  :custom
  (doom-modeline-height 15)
  (doom-modeline-bar-width 6)
  (doom-modeline-lsp t)
 (doom-modeline-github nil)
  (doom-modeline-mu4e nil)
  (doom-modeline-irc t)
  (doom-modeline-minor-modes t)
  (doom-modeline-persp-name nil)
  (doom-modeline-buffer-file-name-style 'truncate-except-project)
  (doom-modeline-major-mode-icon nil))


#+end_src


;; #+begin_src emacs-lisp
;;   (use-package doom-modeline
;;  :init (doom-modeline-mode 1)
;;)
;;  #+end_src
* WHICK KEY
[[https://github.com/justbur/emacs-which-key][whick-key]] is a useful UI panel that appears when you start pressing any key binding in Emacs to offer you all passible completions for the prefix. For example, if you press ~C-c~ a panel will appear at the botton of the frame displaying all of the bindings under that prefix and which command they run. This is very useful for learning the possible key bindings in the mode of your current buffer.

  #+begin_src emacs-lisp
(use-package which-key
  :defer 0
  :diminish which-key-mode
  :config
  (which-key-mode)
  (setq which-key-idle-delay 0.3))
  #+end_src


* PowerShell Integration In Emacs

#+begin_src emacs-lisp
(defun run-powershell ()
  "Run powershell"
  (interactive)
  (async-shell-command "c:/windows/system32/WindowsPowerShell/v1.0/powershell.exe -Command -"
               nil
               nil))
#+end_src

* ORG CONFIGURATION
** Org-Bullets
org-bullets replaces the heading stars in org-mode buffers with nicer looking characters that you can control. Another option for this is org-superstar-mode which we may cover in a later video.

#+begin_src emacs-lisp
 (use-package org-bullets
  :ensure t
  :hook (org-mode . org-bullets-mode)
  :custom
  (org-bullets-bullet-list '("◉" "○" "●" "○" "●" "○" "●")))
#+end_src
** ORG-Fonts
   Set the header font sizes to something more palatable. A fair amount of inspiration has been taken from this [[https://zzamboni.org/post/beautifying-org-mode-in-emacs/][blog-post]].
   #+begin_src emacs-lisp
;; Increase the size of various headings
(set-face-attribute 'org-document-title nil :font "Iosevka Aile" :weight 'bold :height 1.3)
(dolist (face '((org-level-1 . 1.2)
                (org-level-2 . 1.1)
                (org-level-3 . 1.05)
                (org-level-4 . 1.0)
                (org-level-5 . 1.1)
                (org-level-6 . 1.1)
                (org-level-7 . 1.1)
                (org-level-8 . 1.1)))
  (set-face-attribute (car face) nil :font "Iosevka Aile" :weight 'medium :height (cdr face)))

;; Make sure org-indent face is available
(require 'org-indent)

;; Ensure that anything that should be fixed-pitch in Org files appears that way
 (set-face-attribute 'org-block nil :foreground nil :inherit 'fixed-pitch)
(set-face-attribute 'org-table nil  :inherit 'fixed-pitch)
(set-face-attribute 'org-formula nil  :inherit 'fixed-pitch)
 (set-face-attribute 'org-code nil   :inherit '(shadow fixed-pitch))
(set-face-attribute 'org-indent nil :inherit '(org-hide fixed-pitch))
(set-face-attribute 'org-verbatim nil :inherit '(shadow fixed-pitch))
(set-face-attribute 'org-special-keyword nil :inherit '(font-lock-comment-face fixed-pitch))
(set-face-attribute 'org-meta-line nil :inherit '(font-lock-comment-face fixed-pitch))
(set-face-attribute 'org-checkbox nil :inherit 'fixed-pitch)

;; Get rid of the background on column views
(set-face-attribute 'org-column nil :background nil)
(set-face-attribute 'org-column-title nil :background nil)
   #+end_src

** Structure Templates
Org Mode’s structure templates feature enables you to quickly insert code blocks into your Org files in combination with org-tempo by typing  followed by the template name like <el or <py and then press TAB. For example, to insert an empty emacs-lisp block below, you can type <el and press TAB to expand into such a block.

You can add more src block templates below by copying one of the lines and changing the two strings at the end, the first to be the template name and the second to contain the name of the language as it is known by Org Babel.


| Typing the below + TAB | Expands to ...                          |
|------------------------+-----------------------------------------|
| <a                     | '#+BEGIN_EXPORT ascii' … '#+END_EXPORT  |
| <c                     | '#+BEGIN_CENTER' … '#+END_CENTER'       |
| <C                     | '#+BEGIN_COMMENT' … '#+END_COMMENT'     |
| <e                     | '#+BEGIN_EXAMPLE' … '#+END_EXAMPLE'     |
| <E                     | '#+BEGIN_EXPORT' … '#+END_EXPORT'       |
| <h                     | '#+BEGIN_EXPORT html' … '#+END_EXPORT'  |
| <l                     | '#+BEGIN_EXPORT latex' … '#+END_EXPORT' |
| <q                     | '#+BEGIN_QUOTE' … '#+END_QUOTE'         |
| <s                     | '#+BEGIN_SRC' … '#+END_SRC'             |
| <v                     | '#+BEGIN_VERSE' … '#+END_VERSE'         |


#+begin_src emacs-lisp

(with-eval-after-load 'org
  ;; This is needed as of Org 9.2
  (require 'org-tempo)

(add-to-list 'org-structure-template-alist '("sh" . "src sh"))
(add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
(add-to-list 'org-structure-template-alist '("sc" . "src scheme"))
(add-to-list 'org-structure-template-alist '("ts" . "src typescript"))
(add-to-list 'org-structure-template-alist '("py" . "src python"))
(add-to-list 'org-structure-template-alist '("go" . "src go"))
(add-to-list 'org-structure-template-alist '("yaml" . "src yaml"))
(add-to-list 'org-structure-template-alist '("json" . "src json"))
)

#+end_src

*** Source Code Block Syntax Highlighting
We want the same syntax highlighting in source blocks as in the native language files.

#+begin_src emacs-lisp
(setq org-src-fontify-natively t
    org-src-tab-acts-natively t
    org-confirm-babel-evaluate nil
    org-edit-src-content-indentation 0)
#+end_src
** Update Table of Contents On Save
   It's nice to have a table of contents section for long literate configuration files(like this one) so I use =org-make-toc= to automatically update the TOC in any header with a property named =TOC=.
   #+begin_src emacs-lisp

(use-package org-make-toc
  :hook (org-mode . org-make-toc-mode))


   #+end_src
** Presentations ORG_MODE
*** ORG PRESENT
   =org-present= is the package I use for giving presentation in Emacs. I like it because it's simple and allows me to customize the display of it pretty easily.
   #+begin_src emacs-lisp

(defun dw/org-present-prepare-slide ()
  (org-overview)
  (org-show-entry)
  (org-show-children))

(defun dw/org-present-hook ()
  (setq-local face-remapping-alist '((default (:height 1.5) variable-pitch)
                                     (header-line (:height 4.5) variable-pitch)
                                     (org-document-title (:height 1.75) org-document-title)
                                     (org-code (:height 1.55) org-code)
                                     (org-verbatim (:height 1.55) org-verbatim)
                                     (org-block (:height 1.25) org-block)
                                     (org-block-begin-line (:height 0.7) org-block)))
  (setq header-line-format " ")
  (org-appear-mode -1)
  (org-display-inline-images)
  (dw/org-present-prepare-slide))

(defun dw/org-present-quit-hook ()
  (setq-local face-remapping-alist '((default variable-pitch default)))
  (setq header-line-format nil)
  (org-present-small)
  (org-remove-inline-images)
  (org-appear-mode 1))

(defun dw/org-present-prev ()
  (interactive)
  (org-present-prev)
  (dw/org-present-prepare-slide))

(defun dw/org-present-next ()
  (interactive)
  (org-present-next)
  (dw/org-present-prepare-slide))

(use-package org-present
  :bind (:map org-present-mode-keymap
         ("C-c C-j" . dw/org-present-next)
         ("C-c C-k" . dw/org-present-prev))
  :hook ((org-present-mode . dw/org-present-hook)
         (org-present-mode-quit . dw/org-present-quit-hook)))


   #+end_src
*** Org-Tree-Slide
    I previously used =org-tree-slide= for presentations before trying out =org-present=. I'm keeping my old configuration around here just in case I need to use it again!
    #+begin_src emacs-lisp

(defun dw/org-start-presentation ()
  (interactive)
  (org-tree-slide-mode 1)
  (setq text-scale-mode-amount 3)
  (text-scale-mode 1))

(defun dw/org-end-presentation ()
  (interactive)
  (text-scale-mode 0)
  (org-tree-slide-mode 0))

(use-package org-tree-slide
  :defer t
  :after org
  :commands org-tree-slide-mode
  :config
  (evil-define-key 'normal org-tree-slide-mode-map
    (kbd "q") 'dw/org-end-presentation
    (kbd "C-j") 'org-tree-slide-move-next-tree
    (kbd "C-k") 'org-tree-slide-move-previous-tree)
  (setq org-tree-slide-slide-in-effect nil
        org-tree-slide-activate-message "Presentation started."
        org-tree-slide-deactivate-message "Presentation ended."
        org-tree-slide-header t))


    #+end_src

** Center Org Buffers
   We use [[https://github.com/joostkremers/visual-fill-column][visual-fill-column]] to center =org-mode= buffers for a more pleasing writing experience as it centers the contents of the buffer horizontally to seem more like you are editing a document. This is really a matter of personal preference so you can remove the block below if you don't like the behavior.
   I don't personally don't like it. But still I want to include the code.
 ;;  #+begin_src emacs-lisp

;;(defun efs/org-mode-visual-fill ()
;;  (setq visual-fill-column-width 100
;;        visual-fill-column-center-text t)
;;  (visual-fill-column-mode 1))

;;(use-package visual-fill-column
;;  :hook (org-mode . efs/org-mode-visual-fill))


 ;;  #+end_src

* SHELLS WITHIN EMACS

** Eshell
Eshell is an Emacs 'shell' that is written in Elisp.

#+begin_src emacs-lisp
(use-package eshell-syntax-highlighting
  :ensure t
  :after esh-mode
  :config
  (eshell-syntax-highlighting-global-mode +1))

(setq eshell-rc-script (concat user-emacs-directory "eshell/profile")
      eshell-aliases-file (concat user-emacs-directory "eshell/aliases")
      eshell-history-size 5000
      eshell-buffer-maximum-lines 5000
      eshell-hist-ignoredups t
      eshell-scroll-to-bottom-on-input t
      eshell-destroy-buffer-when-process-dies t
)


;; This prompt function mostly replicates my custom zsh prompt setup
;; that is powered by github.com/denysdovhan/spaceship-prompt.
(defun dw/eshell-prompt ()
  (let ((current-branch (magit-get-current-branch))
        (package-version (dw/get-current-package-version)))
    (concat
     "\n"
     (propertize (system-name) 'face `(:foreground "#62aeed"))
     (propertize " ॐ " 'face `(:foreground "white"))
     (propertize (dw/get-prompt-path) 'face `(:foreground "#82cfd3"))
     (when current-branch
       (concat
        (propertize " • " 'face `(:foreground "white"))
        (propertize (concat " " current-branch) 'face `(:foreground "#c475f0"))))
     (when package-version
       (concat
        (propertize " @ " 'face `(:foreground "white"))
        (propertize package-version 'face `(:foreground "#e8a206"))))
     (propertize " • " 'face `(:foreground "white"))
     (propertize (format-time-string "%I:%M:%S %p") 'face `(:foreground "#5a5b7f"))
     (if (= (user-uid) 0)
         (propertize "\n#" 'face `(:foreground "red2"))
       (propertize "\nλ" 'face `(:foreground "#aece4a")))
     (propertize " " 'face `(:foreground "white")))))



(defun dw/eshell-configure ()
  (require 'evil-collection-eshell)
  (evil-collection-eshell-setup)

  (use-package xterm-color)

  (push 'eshell-tramp eshell-modules-list)
  (push 'xterm-color-filter eshell-preoutput-filter-functions)
  (delq 'eshell-handle-ansi-color eshell-output-filter-functions)

  ;; Save command history when commands are entered
  (add-hook 'eshell-pre-command-hook 'eshell-save-some-history)

  (add-hook 'eshell-before-prompt-hook
            (lambda ()
              (setq xterm-color-preserve-properties t)))

  ;; Truncate buffer for performance
  (add-to-list 'eshell-output-filter-functions 'eshell-truncate-buffer)

  ;; We want to use xterm-256color when running interactive commands
  ;; in eshell but not during other times when we might be launching
  ;; a shell command to gather its output.
  (add-hook 'eshell-pre-command-hook
            (lambda () (setenv "TERM" "xterm-256color")))
  (add-hook 'eshell-post-command-hook
            (lambda () (setenv "TERM" "dumb")))

  ;; Use completion-at-point to provide completions in eshell
  (define-key eshell-mode-map (kbd "<tab>") 'completion-at-point)

  ;; Initialize the shell history
  (eshell-hist-initialize)

 ;; (evil-define-key '(normal insert visual) eshell-mode-map (kbd "C-r") 'consult-history)
 ;; (evil-define-key '(normal insert visual) eshell-mode-map (kbd "<home>") 'eshell-bol)
 ;; (evil-normalize-keymaps)
   (setq eshell-prompt-function      'dw/eshell-prompt
        eshell-prompt-regexp        "^λ "
        eshell-history-size         10000
        eshell-buffer-maximum-lines 10000
        eshell-hist-ignoredups t
        eshell-highlight-prompt t
        eshell-scroll-to-bottom-on-input t
        eshell-prefer-lisp-functions nil))

#+end_src

** Vterm
Vterm is a terminal emulator within Emacs. The 'shell-file-name' settings sets the shell to be used in M-x shell, M-x term, M-x ansi-term and M-x vterm. By default, the shell is set to "cmd" but could change it to "pwsh" if you prefer.


# We can't install vterm in windows 10 for now. Development is on progress. So let's see it in future.

* IVY and Counsel

[[https://oremacs.com/swiper/][Ivy]] is an excellent completion framework for Emacs. It provides a minimal yet powerful selection menu that appears when you open files, switch buffers, and for many other tasks in Emacs. Counsel is a customized set of commands to replace `find-file` with `counsel-find-file`, etc which provide useful commands for each of the default completion commands.

[[https://github.com/Yevgnen/ivy-rich][Ivy-rich]] adds extra columns to a few of the Counsel Commands to provide more information about each item.

#+begin_src emacs-lisp

(use-package ivy

  :diminish
  :bind (("C-s" . swiper)
         :map ivy-minibuffer-map
         ("TAB" . ivy-alt-done)
         ("C-l" . ivy-alt-done)
         ("C-j" . ivy-next-line)
         ("C-k" . ivy-previous-line)
         :map ivy-switch-buffer-map
         ("C-k" . ivy-previous-line)
         ("C-l" . ivy-done)
         ("C-d" . ivy-switch-buffer-kill)
         :map ivy-reverse-i-search-map
         ("C-k" . ivy-previous-line)
         ("C-d" . ivy-reverse-i-search-kill))
  :config
  (ivy-mode 1))

(use-package ivy-rich

  :after ivy
  :init
  (ivy-rich-mode 1))

(use-package counsel

  :bind (("C-M-j" . 'counsel-switch-buffer) 
         :map minibuffer-local-map
         ("C-r" . 'counsel-minibuffer-history))


  :config
  (counsel-mode 1))


#+end_src


* Helpful Help Commands
  [[https://github.com/Wilfred/helpful][Helpful]] adds a lot of very helpful (get it?) information to Emacs’ describe- command buffers. For example, if you use describe-function, you will not only get the documentation about the function, you will also see the source code of the function and where it gets used in other places in the Emacs configuration. It is very useful for figuring out how things work in Emacs.

  #+begin_src emacs-lisp

(use-package helpful
  :commands (helpful-callable helpful-variable helpful-command helpful-key)
  :custom
  (counsel-describe-function-function #'helpful-callable)
  (counsel-describe-variable-function #'helpful-variable)
  :bind
  ([remap describe-function] . counsel-describe-function)
  ([remap describe-command] . helpful-command)
  ([remap describe-variable] . counsel-describe-variable)
  ([remap describe-key] . helpful-key))


  #+end_src

* DIRED Configuration
  #+begin_src emacs-lisp

     (use-package dired
       :ensure nil
       :commands (dired dired-jump)
       :bind (("C-x C-j" . dired-jump))
       :custom
       (setq dired-listing-switches "-agho --group-directories-first")
     (global-set-key 'normal 'diredmode-map
       "h" 'dired-single-up-directory
       "H" 'dired-omit-mode
       "l" 'dired-single-buffer
       "y" 'dired-ranger-copy
       "X" 'dired-ranger-move
       "p" 'dired-ranger-paste)
     ;;  :config
      ;; (evil-collection-define-key 'normal 'dired-mode-map
       ;;  "h" 'dired-single-up-directory
	;; "l" 'dired-single-buffer))
     )
     (use-package dired-single
       :commands (dired dired-jump))

     (use-package all-the-icons-dired
       :hook (dired-mode . all-the-icons-dired-mode))
  (use-package dired-rainbow
      :defer 2
      :config
    ;;  (dired-rainbow-define-chmod directory "#6cb2eb" "d.*")
      (dired-rainbow-define html "#eb5286" ("css" "less" "sass" "scss" "htm" "html" "jhtm" "mht" "eml" "mustache" "xhtml"))
      (dired-rainbow-define xml "#f2d024" ("xml" "xsd" "xsl" "xslt" "wsdl" "bib" "json" "msg" "pgn" "rss" "yaml" "yml" "rdata"))
      (dired-rainbow-define document "#9561e2" ("docm" "doc" "docx" "odb" "odt" "pdb" "pdf" "ps" "rtf" "djvu" "epub" "odp" "ppt" "pptx"))
      (dired-rainbow-define markdown "#ffed4a" ("org" "etx" "info" "markdown" "md" "mkd" "nfo" "pod" "rst" "tex" "textfile" "txt"))
      (dired-rainbow-define database "#6574cd" ("xlsx" "xls" "csv" "accdb" "db" "mdb" "sqlite" "nc"))
      (dired-rainbow-define media "#de751f" ("mp3" "mp4" "mkv" "MP3" "MP4" "avi" "mpeg" "mpg" "flv" "ogg" "mov" "mid" "midi" "wav" "aiff" "flac"))
      (dired-rainbow-define image "#f66d9b" ("tiff" "tif" "cdr" "gif" "ico" "jpeg" "jpg" "png" "psd" "eps" "svg"))
      (dired-rainbow-define log "#c17d11" ("log"))
      (dired-rainbow-define shell "#f6993f" ("awk" "bash" "bat" "sed" "sh" "zsh" "vim"))
      (dired-rainbow-define interpreted "#38c172" ("py" "ipynb" "rb" "pl" "t" "msql" "mysql" "pgsql" "sql" "r" "clj" "cljs" "scala" "js"))
      (dired-rainbow-define compiled "#4dc0b5" ("asm" "cl" "lisp" "el" "c" "h" "c++" "h++" "hpp" "hxx" "m" "cc" "cs" "cp" "cpp" "go" "f" "for" "ftn" "f90" "f95" "f03" "f08" "s" "rs" "hi" "hs" "pyc" ".java"))
      (dired-rainbow-define executable "#8cc4ff" ("exe" "msi"))
      (dired-rainbow-define compressed "#51d88a" ("7z" "zip" "bz2" "tgz" "txz" "gz" "xz" "z" "Z" "jar" "war" "ear" "rar" "sar" "xpi" "apk" "xz" "tar"))
      (dired-rainbow-define packaged "#faad63" ("deb" "rpm" "apk" "jad" "jar" "cab" "pak" "pk3" "vdf" "vpk" "bsp"))
      (dired-rainbow-define encrypted "#ffed4a" ("gpg" "pgp" "asc" "bfe" "enc" "signature" "sig" "p12" "pem"))
      (dired-rainbow-define fonts "#6cb2eb" ("afm" "fon" "fnt" "pfb" "pfm" "ttf" "otf"))
      (dired-rainbow-define partition "#e3342f" ("dmg" "iso" "bin" "nrg" "qcow" "toast" "vcd" "vmdk" "bak"))
      (dired-rainbow-define vc "#0074d9" ("git" "gitignore" "gitattributes" "gitmodules"))
      (dired-rainbow-define-chmod executable-unix "#38c172" "-.*x.*"))


  (use-package dired-single
    :defer t)

  (use-package dired-ranger
    :defer t)

  (use-package dired-collapse
    :defer t)
  #+end_src

* DEVELOPMENT
** Languages
*** IDE Features With lsp-mode
**** lsp-mode
     We use the excellent [[https://emacs-lsp.github.io/lsp-mode/][lsp-mode]] to enable IDE-like functionality for many different programming languages via “language servers” that speak the [[https://microsoft.github.io/language-server-protocol/][Language Server Protocol]]. Before trying to set up =lsp-mode= for a particular language, check out the [[Y][documetation for your language]] so that you can learn which language servers are available and how to install them.

     The ~lsp-keymap-prefix~ setting enables you to define a prefix for where ~lsp-mode~'s default keybindings will be added. I *highly recommend* using the prefix to find out what you can do with ~lsp-mode~ in a buffer.

     The =which-key= integration adds helpful descriptions of the various keys so you should be able to learn a lot just by pressing ~C-c l~ in a =lsp-mode= buffer and trying different things that you find there.

     #+begin_src emacs-lisp

(defun efs/lsp-mode-setup ()
  (setq lsp-headerline-breadcrumb-segments '(path-up-to-project file symbols))
  (lsp-headerline-breadcrumb-mode))

(use-package lsp-mode
  :commands (lsp lsp-deferred)
  :hook (lsp-mode . efs/lsp-mode-setup)
  :init
  (setq lsp-keymap-prefix "C-c l")  ;; Or 'C-l', 's-l'
  :config
  (lsp-enable-which-key-integration t))
;; keybindings using general.el
(dw/leader-key-def
  "l"  '(:ignore t :which-key "lsp")
  "ld" 'xref-find-definitions
  "lr" 'xref-find-references
  "ln" 'lsp-ui-find-next-reference
  "lp" 'lsp-ui-find-prev-reference
  "ls" 'counsel-imenu
  "le" 'lsp-ui-flycheck-list
  "lS" 'lsp-ui-sideline-mode
  "lX" 'lsp-execute-code-action)

     #+end_src
**** lsp-ui
     [[https://emacs-lsp.github.io/lsp-ui/][lsp-ui]] is a set of UI enhancements built on top of =lsp-mode= which make Emacs feel even more like an IDE. Check out the screenshots on the =lsp-ui= homepage(linked at the beginning of this paragraph) to see examples of what it can do.
     #+begin_src emacs-lisp
(use-package lsp-ui
  :hook (lsp-mode . lsp-ui-mode)
  :config
  (setq lsp-ui-sideline-enable t)
  (setq lsp-ui-sideline-show-hover nil)
  (setq lsp-ui-doc-position 'bottom)
  (lsp-ui-doc-show))
     #+end_src
**** lsp-treemacs
     [[https://github.com/emacs-lsp/lsp-treemacs][lsp-treemacs]] provides nice tree views for different aspects of your code like symbols in a file, references of a symbol, or diagnostic messages(errors and warnings) that are found in your code.

     Try these commands with =M-x=:

     -> ~lsp-treemacs-symbols~ - Show a tree view of the symbols in the currents file
     -> ~lsp-treemacs-references~ - Show a tree view for the references of the symbol under the cursor.
     -> ~lsp-treemacs-error-list~ - Show a tree view for the diagnostic messages in the project.

     This package is built on the [[https://github.com/Alexander-Miller/treemacs][treemacs]] package which might be of some interest to you if you like to have a file browser at the left side of your screen in your editor.
     #+begin_src emacs-lisp
     (use-package lsp-treemacs
       :after lsp)
     #+end_src
**** lsp-ivy
     [[https://github.com/emacs-lsp/lsp-ivy][lsp-ivy]] integrates Ivy with =lsp-mode= to make it easy to  search for things by name in your code. When you run these commands, a prompt will appear in the minibuffer allowing you to type part of the name of a symbol in your code. Results will be populated in the minibuffer so that you can find what you’re looking for and jump to that location in the code upon selecting the result.
     Try these commands with =M-x=:
     -> ~lsp-ivy-workspace-symbol~ - Search for a symbol name in the current project workspace
     -> ~lsp-ivy-global-workspace-symbol~ - Search for a symbol name in all active project workspaces

     #+begin_src emacs-lisp
     (use-package lsp-ivy
       :after lsp)
     #+end_src

*** Debugging with dap-mode
    [[https://emacs-lsp.github.io/dap-mode/][dap-mode]] is an excellent package for bringing rich debugging capabilities to Emacs via the [[https://microsoft.github.io/debug-adapter-protocol/][Debug Adapter Protocol]]. You should check out the [[https://emacs-lsp.github.io/dap-mode/page/configuration/][configuration docs]] to learn how to configure the debugger for your language. Also make sure to check out the documentation for the debug adapter to see what configuration parameters are available to use for our debug templates!

    #+begin_src emacs-lisp

(use-package dap-mode
  ;; Uncomment the config below if you want all UI panes to be hidden by default!
  ;; :custom
  ;; (lsp-enable-dap-auto-configure nil)
  ;; :config
  ;; (dap-ui-mode 1)
  :commands dap-debug
  :config
  ;; Set up Node debugging
  (require 'dap-node)
  (dap-node-setup) ;; Automatically installs Node debug adapter if needed

  ;; Bind `C-c l d` to `dap-hydra` for easy access
  (general-define-key
    :keymaps 'lsp-mode-map
    :prefix lsp-keymap-prefix
    "d" '(dap-hydra t :wk "debugger")))


    #+end_src

    
*** Python
    We use =lsp-mode= and =dap-mode= to provide a more complete development environment for Python in Emacs. Check out the =pyls= [[https://emacs-lsp.github.io/lsp-mode/page/lsp-pyls/][configuration]] in the =lsp-mode=!
    ~pip install --user "pythin-language-server[all]"~
    There are a number of other language servers for Python so if you find that =pyls= doesn't work for you, consult the =lsp-mode= [[https://emacs-lsp.github.io/lsp-mode/page/languages/][language configuration documentation]] to try the others!
    #+begin_src emacs-lisp
    (use-package python-mode
      :ensure t
      :hook (python-mode . lsp-deferred)
      :custom
      ;;NOTE: Set these if python 3 is called "python3" on your system!
      ;; (python-shell-interpreter "python3")
      ;; (dap-python-executable "python3")
      (dap-python-debugger 'debugpy)
      :config
      (require 'dap-python))
    #+end_src

    You can use the pyvenv package to use =virtualenv= environments in Emacs. The =pyvenv-activate= command should configure Emacs to cause =lsp-mode= and =dap-mode= to use the virtual environment when they are loaded, just select the path to your virtual environment before loading your project.

    #+begin_src emacs-lisp
    (use-package pyvenv
      :after python-mode
      :config
      (pyvenv-mode 1))
    #+end_src


*** Company Mode
    [[http://company-mode.github.io/][Company Mode]] providers a nicer in-buffer completion interface than =completion-at-point= which is more reminiscent of what you would expect from an IDE. We add a simple configuration to make the keybindigs a little more useful(=TAB= now completes teh selection and initiates completion at the current location if needed.
    We also use [[https://github.com/sebastiencs/company-box][company-box]] to further enhance the look of the completions with icons and better overall presentation.
    #+begin_src emacs-lisp
    (use-package company
      :after lsp-mode
      :hook (lsp-mode . company-mode)
      :bind (:map company-active-map
	     ("<tab>" . company-complete-selection))
	    (:map lsp-mode-map
	     ("<tab>". company-indent-or-complete-common))
      :custom
      (company-minimum-prefix-length 1)
      (company-idle-delay 0.0))

    (use-package company-box
      :hook (company-mode . company-box-mode))
    #+end_src

*** lsp-java
    #+begin_src emacs-lisp
    (use-package lsp-java
    :config
    (add-hook 'java-mode-hook 'lsp)
    (setq
	 lsp-java-server-install-dir "~/.emacs.d/java_lsp/"
         lsp-java-workspace-dir "~/Projects/Code/"
	 lsp-java-java-path "C:/Program Files/Java/jdk-16.0.1/bin/java.exe"))
    #+end_src

* Productivity
** snippets
   #+begin_src emacs-lisp

(use-package yasnippet
  :hook (prog-mode . yas-minor-mode)
  :config
  (yas-reload-all))


   #+end_src
** Rainbow Delimiters
   [[https://github.com/Fanael/rainbow-delimiters][Rainbow-delimiters]] is useful in programming modes because it colorizes nested parentheses and brackets according to their nesting depth. This makes it a lot easier to visually match parentheses in Emacs lisp code without having to count them yourself.
   #+begin_src emacs-lisp
   (use-package rainbow-delimiters
    :hook (prog-mode . rainbow-delimiters-mode))
   #+end_src
** Syntax checking with Flycheck
   #+begin_src emacs-lisp

(use-package flycheck
  :defer t
  :hook (lsp-mode . flycheck-mode))


   #+end_src
** Smart Parens
   #+begin_src emacs-lisp

(use-package smartparens
  :hook (prog-mode . smartparens-mode))
   #+end_src
** Rainbow Mode
   Sets the background of HTML color strings in buffers to be the color mentioned.
   #+begin_src emacs-lisp

(use-package rainbow-mode
  :defer t
  :hook (org-mode
         emacs-lisp-mode
         web-mode
         typescript-mode
         js2-mode))


   #+end_src

* Magit
  [[https://magit.vc/][Magit]] is the best Git interfac in this world. Common Git operations are easy to execute quickly using Magit’s command panel system.
  #+begin_src emacs-lisp

;;  (use-package magit			
;;  :ensure t
;;   :commands magit-status
;;  :custom
;; (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))

;; NOTE: Make sure to configure a GitHub token before using this package!
;; - https://magit.vc/manual/forge/Token-Creation.html#Token-Creation
  ;; - https://magit.vc/manual/ghub/Getting-Started.html#Getting-Started
;;  (use-package forge
;;   :after magit)


  #+end_src
  
* RSS with Elfeed
  [[https://github.com/skeeto/elfeed][Elfeed]] looks like a great RSS feed reader. Not using it much yet, but definitely looking forward to using it to keep track of a few different blogs I follow. Also seems to be great for following subreddits like /r/Emacs.
  #+begin_src emacs-lisp

(use-package elfeed
  :commands elfeed
  :config
  (setq elfeed-feeds
    '("https://nullprogram.com/feed/"
      "https://ambrevar.xyz/atom.xml"
      "https://guix.gnu.org/feeds/blog.atom"
      "https://valdyas.org/fading/feed/"
      "https://www.reddit.com/r/emacs/.rss")))
  #+end_src

* Calendar
  [[https://github.com/kiwanami/emacs-calfw][calfw]] is a gorgeous calendar UI that is able to show all of my scheduled ORG Agenda items.
  #+begin_src emacs-lisp

(use-package calfw
  :disabled
  :commands cfw:open-org-calendar
  :config
  (setq cfw:fchar-junction ?╋
        cfw:fchar-vertical-line ?┃
        cfw:fchar-horizontal-line ?━
        cfw:fchar-left-junction ?┣
        cfw:fchar-right-junction ?┫
        cfw:fchar-top-junction ?┯
        cfw:fchar-top-left-corner ?┏
        cfw:fchar-top-right-corner ?┓)

  (use-package calfw-org
    :config
    (setq cfw:org-agenda-schedule-args '(:timestamp))))

(dw/leader-key-def
  "cc"  '(cfw:open-org-calendar :which-key "calendar"))


  #+end_src

* 

* LAST: RUNTIME PERFORMANCE
  Dial the GC threshold back down so that garbage collection happends more frequently but in less time.

  #+begin_src emacs-lisp
  ;;Make gc pauses faster by decreasing the threshold.
(setq gc-cons-threshold (* 2 1000 1000))
  #+end_src
